CREATE TABLE "DBA_ST"."INVOICE" 
   (	"TILL_NO" NUMBER(3,0) NOT NULL ENABLE, 
	"INVOICE_NO" NUMBER(6,0) NOT NULL ENABLE, 
	"CASHIER_NO" NUMBER(3,0) NOT NULL ENABLE, 
	"INVOICE_DATE" DATE NOT NULL ENABLE, 
	"INVOICE_TIME" NUMBER(4,0) NOT NULL ENABLE, 
	"NBR_LINES" NUMBER(5,0) NOT NULL ENABLE, 
	"NBR_VOID_LINES" NUMBER(5,0) NOT NULL ENABLE, 
	"TOT_NM_FOOD" NUMBER(15,2) NOT NULL ENABLE, 
	"TOT_NM_NFOOD" NUMBER(15,2) NOT NULL ENABLE, 
	"TOT_MM_FOOD" NUMBER(15,2) NOT NULL ENABLE, 
	"TOT_MM_NFOOD" NUMBER(15,2) NOT NULL ENABLE, 
	"FEE_AMOUNT" NUMBER(9,2) NOT NULL ENABLE, 
	"FEE_STATUS" NUMBER NOT NULL ENABLE, 
	"PROC_IND" NUMBER(1,0) NOT NULL ENABLE, 
	"CUST_NO" NUMBER(6,0) NOT NULL ENABLE, 
	"STORE_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"BONUS_POINTS" NUMBER(7,0) NOT NULL ENABLE, 
	"TILL_STATUS" NUMBER(1,0) NOT NULL ENABLE, 
	"CONS_MODE" NUMBER(1,0) NOT NULL ENABLE, 
	"TOT_PACK" NUMBER(5,0) NOT NULL ENABLE, 
	"CASH_CHANGE" NUMBER(15,2) NOT NULL ENABLE, 
	"ROUNDING_DIFF" NUMBER(15,2) NOT NULL ENABLE, 
	"INVOICE_TYPE" NUMBER(1,0) NOT NULL ENABLE, 
	"TTAX_COND" VARCHAR2(2) NOT NULL ENABLE, 
	"SUPERVISOR_CD" VARCHAR2(6), 
	"INV_STATUS" VARCHAR2(1) NOT NULL ENABLE, 
	"FISC_POS_ID" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"FISC_INVOICE_NO" NUMBER(8,0), 
	"FISC_INV_NO_END" NUMBER(8,0), 
	"ORIG_FISC_POS_ID" NUMBER(4,0), 
	"ORIG_FISC_INV_NO" NUMBER(8,0), 
	"ORG_TILL_NO" NUMBER(3,0), 
	"ORG_INVOICE_NO" NUMBER(6,0), 
	"VOUCHER_NO" NUMBER(20,0), 
	 CONSTRAINT "INV_PK" PRIMARY KEY ("TILL_NO", "INVOICE_TYPE", "INVOICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MBS_ST_INDEX_00"  ENABLE, 
	 CHECK ( till_no BETWEEN 0 AND 999 ) ENABLE, 
	 CHECK ( invoice_no BETWEEN 0 AND 999999 ) ENABLE, 
	 CHECK ( cashier_no BETWEEN 1 AND 999 ) ENABLE, 
	 CHECK ( invoice_time BETWEEN 0 AND 2359 ) ENABLE, 
	 CHECK ( nbr_lines BETWEEN 0 AND 99999 ) ENABLE, 
	 CHECK ( nbr_void_lines BETWEEN 0 AND 99999 ) ENABLE, 
	 CHECK ( fee_amount BETWEEN 0 AND 9999999.99 ) ENABLE, 
	 CHECK ( fee_status BETWEEN 0 AND 3 ) ENABLE, 
	 CHECK ( cust_no BETWEEN 1 AND 999999 ) ENABLE, 
	 CHECK ( store_no BETWEEN 1 AND 99 ) ENABLE, 
	 CHECK ( bonus_points BETWEEN 0 AND 9999999 ) ENABLE, 
	 CHECK ( till_status BETWEEN 0 AND 9 ) ENABLE, 
	 CHECK ( cons_mode BETWEEN 0 AND 9 ) ENABLE, 
	 CONSTRAINT "INV_TIL_FK" FOREIGN KEY ("TILL_NO")
	  REFERENCES "DBA_ST"."TILL" ("TILL_NO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MBS_ST_DATA_00" ;