/*Toda las tablas*/

SELECT i.INVOICE_NO AS invoice, il.INVOICE_NO AS line, ia.INVOICE_NO AS afip, ip.INVOICE_NO AS payment, 
	im.INVOICE_NO AS multisam, ipi.INVOICE_NO AS item, iv.INVOICE_NO AS vat, it.INVOICE_NO AS tax FROM INVOICE i
LEFT JOIN INVOICE_LINE il ON IL.INVOICE_NO=i.INVOICE_NO AND il.INVOICE_TYPE=i.INVOICE_TYPE AND il.TILL_No=i.TILL_NO 
LEFT JOIN INVOICE_AFIP ia ON ia.INVOICE_NO=i.INVOICE_NO AND ia.INVOICE_TYPE=i.INVOICE_TYPE AND ia.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_PAYMENT ip ON ip.INVOICE_NO=i.INVOICE_NO AND ip.INVOICE_TYPE=i.INVOICE_TYPE AND ip.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_MULTISAM im ON im.INVOICE_NO=i.INVOICE_NO AND im.INVOICE_TYPE=i.INVOICE_TYPE AND im.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_PAYMENT_ITEM ipi ON ipi.INVOICE_NO=i.INVOICE_NO AND ipi.INVOICE_TYPE=i.INVOICE_TYPE AND ipi.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_VAT iv ON iv.INVOICE_NO=i.INVOICE_NO AND iv.INVOICE_TYPE=i.INVOICE_TYPE AND iv.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_TAX it ON it.INVOICE_NO=i.INVOICE_NO AND it.INVOICE_TYPE=i.INVOICE_TYPE AND it.TILL_No=i.TILL_No 
WHERE 
i.INVOICE_NO		is null
or il.INVOICE_NO  is null
or ia.INVOICE_NO  is null
or ip.INVOICE_NO  is null
or im.INVOICE_NO  is null
or ipi.INVOICE_NO is null
or iv.INVOICE_NO  is null
or it.INVOICE_NO  is NULL

/*Tablas importantes*/

SELECT i.INVOICE_NO AS invoice, il.INVOICE_NO AS line, ia.INVOICE_NO AS afip, 
			ip.INVOICE_NO AS payment, iv.INVOICE_NO AS vat FROM INVOICE i
LEFT JOIN INVOICE_LINE il ON IL.INVOICE_NO=i.INVOICE_NO AND il.INVOICE_TYPE=i.INVOICE_TYPE AND il.TILL_No=i.TILL_NO 
LEFT JOIN INVOICE_AFIP ia ON ia.INVOICE_NO=i.INVOICE_NO AND ia.INVOICE_TYPE=i.INVOICE_TYPE AND ia.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_PAYMENT ip ON ip.INVOICE_NO=i.INVOICE_NO AND ip.INVOICE_TYPE=i.INVOICE_TYPE AND ip.TILL_No=i.TILL_No 
LEFT JOIN INVOICE_VAT iv ON iv.INVOICE_NO=i.INVOICE_NO AND iv.INVOICE_TYPE=i.INVOICE_TYPE AND iv.TILL_No=i.TILL_No  
WHERE 
i.INVOICE_NO		is null
or il.INVOICE_NO  is null
or ia.INVOICE_NO  is null
or ip.INVOICE_NO  is null
or iv.INVOICE_NO  is null